// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbrayxmqzdxsmhqmzygc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBicmF5eG1xemR4c21ocW16eWdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDU5NDUsImV4cCI6MjA2ODgyMTk0NX0.n4SNUD5IOyT2Pjp63sQdDFWIoIwAbzCWiwU2-jjjngo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});